/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.telaPrincipal;

import javax.swing.JFrame;

import telas.telaProduto.TelaCadastroProduto;
import telas.telaProduto.TelaConsultaProduto;




public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        this.setTitle("SOLD IT");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuConsuCadProd = new javax.swing.JMenuItem();
        jMenuConsuCadProd1 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/resources/informatica.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu2.setText("Produto");

        jMenuConsuCadProd.setText("Cadastrar produto");
        jMenuConsuCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsuCadProdActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuConsuCadProd);

        jMenuConsuCadProd1.setText("Consultar produto");
        jMenuConsuCadProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsuCadProd1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuConsuCadProd1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    TelaCadastroProduto tCadastProd = null;
    
    TelaConsultaProduto tConsultarproduto = null;
    
  

   
      //Chama tela de cadastro Produto.
    private void jMenuConsuCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsuCadProdActionPerformed
        if (tCadastProd == null || !tCadastProd.isDisplayable()) {
            tCadastProd = new TelaCadastroProduto();
            tCadastProd.pack();
            tCadastProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tCadastProd.setLocationRelativeTo(null);
            tCadastProd.setVisible(true);
        }
        tCadastProd.toFront();
    }//GEN-LAST:event_jMenuConsuCadProdActionPerformed
    
    
    //Chama tela de consulta produto.
    private void jMenuConsuCadProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsuCadProd1ActionPerformed

        if (tConsultarproduto == null || !tConsultarproduto.isDisplayable()) {
            tConsultarproduto = new TelaConsultaProduto();
            tConsultarproduto.pack();
            tConsultarproduto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tConsultarproduto.setLocationRelativeTo(null);
            tConsultarproduto.setVisible(true);
        }
        tConsultarproduto.toFront();

    }//GEN-LAST:event_jMenuConsuCadProd1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConsuCadProd;
    private javax.swing.JMenuItem jMenuConsuCadProd1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
